name: Deployment
on: push
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependecies
              run: npm ci
            - name: Lint
              run: npm run lint
            - name: Test code
              run: npm run test
            - name: Build
              run: npm run build
            - name: Deploy
              run: echo "Deploying ..."